-- Better Auth for XerahS Cloud, replacing Supabase Auth.
--
-- 1. Better Auth's tables (generated by `npx auth@1.7.6 generate` from
--    src/lib/better-auth.ts) in their own schema, closed to API roles.
-- 2. Mirroring between Better Auth and the Supabase-shaped auth.users /
--    auth.sessions that the XIP0085 SQL reads, in both directions:
--      better_auth.user    -> auth.users      (insert, update, delete)
--      better_auth.session -> auth.sessions   (insert, update, delete)
--      auth.users delete   -> better_auth.user     (account deletion workflow)
--      auth.sessions delete-> better_auth.session  (sign out everywhere) and
--                             revokes desktop refresh tokens for that grant.
--    Mirrored sessions start at aal1. The app raises them to aal2 only when a
--    second factor or passkey is verified (src/lib/better-auth.ts hooks).

create schema if not exists "better_auth";

create table "better_auth"."user" ("id" uuid default pg_catalog.gen_random_uuid() not null primary key, "name" text not null, "email" text not null unique, "emailVerified" boolean not null, "image" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null, "twoFactorEnabled" boolean);

create table "better_auth"."session" ("id" uuid default pg_catalog.gen_random_uuid() not null primary key, "expiresAt" timestamptz not null, "token" text not null unique, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null, "ipAddress" text, "userAgent" text, "userId" uuid not null references "better_auth"."user" ("id") on delete cascade);

create table "better_auth"."account" ("id" uuid default pg_catalog.gen_random_uuid() not null primary key, "accountId" text not null, "providerId" text not null, "userId" uuid not null references "better_auth"."user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz, "scope" text, "password" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null);

create table "better_auth"."verification" ("id" uuid default pg_catalog.gen_random_uuid() not null primary key, "identifier" text not null, "value" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create table "better_auth"."twoFactor" ("id" uuid default pg_catalog.gen_random_uuid() not null primary key, "secret" text not null, "backupCodes" text not null, "userId" uuid not null references "better_auth"."user" ("id") on delete cascade, "verified" boolean, "failedVerificationCount" integer, "lockedUntil" timestamptz);

create table "better_auth"."passkey" ("id" uuid default pg_catalog.gen_random_uuid() not null primary key, "name" text, "publicKey" text not null, "userId" uuid not null references "better_auth"."user" ("id") on delete cascade, "credentialID" text not null, "counter" integer not null, "deviceType" text not null, "backedUp" boolean not null, "transports" text, "createdAt" timestamptz, "aaguid" text);

create table "better_auth"."jwks" ("id" uuid default pg_catalog.gen_random_uuid() not null primary key, "publicKey" text not null, "privateKey" text not null, "createdAt" timestamptz not null, "expiresAt" timestamptz, "alg" text, "crv" text);

create table "better_auth"."oauthClient" ("id" uuid default pg_catalog.gen_random_uuid() not null primary key, "clientId" text not null unique, "clientSecret" text, "clientDiscoveryId" text, "disabled" boolean, "skipConsent" boolean, "enableEndSession" boolean, "subjectType" text, "scopes" jsonb, "clientCredentialsScopes" jsonb, "userId" uuid references "better_auth"."user" ("id") on delete cascade, "createdAt" timestamptz, "updatedAt" timestamptz, "name" text, "uri" text, "icon" text, "contacts" jsonb, "tos" text, "policy" text, "softwareId" text, "softwareVersion" text, "softwareStatement" text, "redirectUris" jsonb not null, "postLogoutRedirectUris" jsonb, "backchannelLogoutUri" text, "backchannelLogoutSessionRequired" boolean, "tokenEndpointAuthMethod" text, "applicationType" text, "jwks" text, "jwksUri" text, "grantTypes" jsonb, "responseTypes" jsonb, "requirePKCE" boolean, "dpopBoundAccessTokens" boolean, "referenceId" text, "metadata" jsonb);

create table "better_auth"."oauthResource" ("id" uuid default pg_catalog.gen_random_uuid() not null primary key, "identifier" text not null unique, "name" text not null, "accessTokenTtl" integer, "refreshTokenTtl" integer, "signingAlgorithm" text, "signingKeyId" text, "allowedScopes" jsonb, "customClaims" jsonb, "dpopBoundAccessTokensRequired" boolean, "disabled" boolean, "createdAt" timestamptz, "updatedAt" timestamptz, "policyVersion" integer, "metadata" jsonb);

create table "better_auth"."oauthClientResource" ("id" uuid default pg_catalog.gen_random_uuid() not null primary key, "clientId" text not null references "better_auth"."oauthClient" ("clientId") on delete cascade, "resourceId" text not null references "better_auth"."oauthResource" ("identifier") on delete cascade, "metadata" jsonb, "createdAt" timestamptz);

create table "better_auth"."oauthRefreshToken" ("id" uuid default pg_catalog.gen_random_uuid() not null primary key, "token" text not null unique, "clientId" text not null references "better_auth"."oauthClient" ("clientId") on delete cascade, "sessionId" uuid references "better_auth"."session" ("id") on delete set null, "userId" uuid not null references "better_auth"."user" ("id") on delete cascade, "referenceId" text, "authorizationCodeId" text, "resources" jsonb, "requestedUserInfoClaims" jsonb, "expiresAt" timestamptz not null, "createdAt" timestamptz not null, "revoked" timestamptz, "rotatedAt" timestamptz, "rotationReplayResponse" text, "rotationReplayExpiresAt" timestamptz, "authTime" timestamptz, "confirmation" jsonb, "scopes" jsonb not null);

create table "better_auth"."oauthAccessToken" ("id" uuid default pg_catalog.gen_random_uuid() not null primary key, "token" text not null unique, "clientId" text not null references "better_auth"."oauthClient" ("clientId") on delete cascade, "sessionId" uuid references "better_auth"."session" ("id") on delete set null, "userId" uuid references "better_auth"."user" ("id") on delete cascade, "referenceId" text, "authorizationCodeId" text, "resources" jsonb, "requestedUserInfoClaims" jsonb, "refreshId" uuid references "better_auth"."oauthRefreshToken" ("id") on delete cascade, "expiresAt" timestamptz not null, "createdAt" timestamptz not null, "revoked" timestamptz, "confirmation" jsonb, "scopes" jsonb not null);

create table "better_auth"."oauthConsent" ("id" uuid default pg_catalog.gen_random_uuid() not null primary key, "clientId" text not null references "better_auth"."oauthClient" ("clientId") on delete cascade, "userId" uuid references "better_auth"."user" ("id") on delete cascade, "referenceId" text, "resources" jsonb, "requestedUserInfoClaims" jsonb, "scopes" jsonb not null, "createdAt" timestamptz not null, "updatedAt" timestamptz not null);

create table "better_auth"."oauthClientAssertion" ("id" uuid default pg_catalog.gen_random_uuid() not null primary key, "expiresAt" timestamptz not null);

create table "better_auth"."rateLimit" ("id" uuid default pg_catalog.gen_random_uuid() not null primary key, "key" text not null unique, "count" integer not null, "lastRequest" bigint not null);

create index "session_userId_idx" on "better_auth"."session" ("userId");

create index "account_userId_idx" on "better_auth"."account" ("userId");

create index "verification_identifier_idx" on "better_auth"."verification" ("identifier");

create index "twoFactor_secret_idx" on "better_auth"."twoFactor" ("secret");

create index "twoFactor_userId_idx" on "better_auth"."twoFactor" ("userId");

create index "passkey_userId_idx" on "better_auth"."passkey" ("userId");

create index "passkey_credentialID_idx" on "better_auth"."passkey" ("credentialID");

create index "oauthClient_userId_idx" on "better_auth"."oauthClient" ("userId");

create index "oauthClientResource_clientId_idx" on "better_auth"."oauthClientResource" ("clientId");

create index "oauthClientResource_resourceId_idx" on "better_auth"."oauthClientResource" ("resourceId");

create index "oauthRefreshToken_clientId_idx" on "better_auth"."oauthRefreshToken" ("clientId");

create index "oauthRefreshToken_sessionId_idx" on "better_auth"."oauthRefreshToken" ("sessionId");

create index "oauthRefreshToken_userId_idx" on "better_auth"."oauthRefreshToken" ("userId");

create index "oauthRefreshToken_authorizationCodeId_idx" on "better_auth"."oauthRefreshToken" ("authorizationCodeId");

create index "oauthAccessToken_clientId_idx" on "better_auth"."oauthAccessToken" ("clientId");

create index "oauthAccessToken_sessionId_idx" on "better_auth"."oauthAccessToken" ("sessionId");

create index "oauthAccessToken_userId_idx" on "better_auth"."oauthAccessToken" ("userId");

create index "oauthAccessToken_authorizationCodeId_idx" on "better_auth"."oauthAccessToken" ("authorizationCodeId");

create index "oauthAccessToken_refreshId_idx" on "better_auth"."oauthAccessToken" ("refreshId");

create index "oauthConsent_clientId_idx" on "better_auth"."oauthConsent" ("clientId");

create index "oauthConsent_userId_idx" on "better_auth"."oauthConsent" ("userId");

create unique index "oauthClientResource_clientId_resourceId_uidx" on "better_auth"."oauthClientResource" ("clientId", "resourceId");
revoke all on schema better_auth from public, anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Session metadata used for aal2 / recent strong authentication claims
-- ---------------------------------------------------------------------------

alter table auth.sessions add column if not exists strong_auth_at timestamptz;
alter table auth.sessions add column if not exists strong_auth_method text;
alter table auth.sessions add column if not exists kind text not null default 'browser';
-- Desktop grants record the browser session that approved them, so the OAuth
-- server's repeated consentReferenceId calls resolve to one grant.
alter table auth.sessions add column if not exists parent_session_id uuid;
create unique index if not exists sessions_desktop_grant_parent_key
  on auth.sessions (user_id, parent_session_id) where kind = 'desktop_grant';
alter table auth.sessions drop constraint if exists sessions_kind_check;
alter table auth.sessions add constraint sessions_kind_check check (kind in ('browser', 'desktop_grant'));
alter table auth.sessions drop constraint if exists sessions_strong_auth_check;
alter table auth.sessions add constraint sessions_strong_auth_check check (
  (aal = 'aal1' and strong_auth_at is null) or (aal = 'aal2' and strong_auth_at is not null)
);

-- ---------------------------------------------------------------------------
-- better_auth -> auth
-- ---------------------------------------------------------------------------

create or replace function better_auth.mirror_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    delete from auth.users where id = old.id;
    return old;
  end if;

  insert into auth.users (id, email, email_confirmed_at, created_at, updated_at)
  values (
    new.id,
    new.email,
    case when new."emailVerified" then clock_timestamp() end,
    new."createdAt",
    new."updatedAt")
  on conflict (id) do update set
    email = excluded.email,
    -- Keep the original confirmation time; clear it if verification is lost
    -- (for example after an email change).
    email_confirmed_at = case
      when new."emailVerified" then coalesce(auth.users.email_confirmed_at, clock_timestamp())
    end,
    updated_at = excluded.updated_at;
  return new;
end;
$$;

create trigger mirror_user_to_auth
after insert or update or delete on better_auth."user"
for each row execute function better_auth.mirror_user();

create or replace function better_auth.mirror_session()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    delete from auth.sessions where id = old.id and kind = 'browser';
    return old;
  end if;

  insert into auth.sessions (id, user_id, aal, created_at, updated_at, not_after, kind)
  values (new.id, new."userId", 'aal1', new."createdAt", new."updatedAt", new."expiresAt", 'browser')
  on conflict (id) do update set
    updated_at = excluded.updated_at,
    not_after = excluded.not_after;
  return new;
end;
$$;

create trigger mirror_session_to_auth
after insert or update or delete on better_auth.session
for each row execute function better_auth.mirror_session();

-- ---------------------------------------------------------------------------
-- auth -> better_auth (deletions made by the XIP0085 SQL)
-- ---------------------------------------------------------------------------

create or replace function auth.propagate_user_delete()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from better_auth."user" where id = old.id;
  return old;
end;
$$;

create trigger propagate_user_delete
after delete on auth.users
for each row execute function auth.propagate_user_delete();

create or replace function auth.propagate_session_delete()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.kind = 'browser' then
    delete from better_auth.session where id = old.id;
  else
    -- Desktop grant: stop its refresh tokens and outstanding access tokens.
    delete from better_auth."oauthRefreshToken" where "referenceId" = old.id::text;
    delete from better_auth."oauthAccessToken" where "referenceId" = old.id::text;
  end if;
  return old;
end;
$$;

create trigger propagate_session_delete
after delete on auth.sessions
for each row execute function auth.propagate_session_delete();

revoke all on function better_auth.mirror_user(), better_auth.mirror_session(),
  auth.propagate_user_delete(), auth.propagate_session_delete() from public, anon, authenticated, service_role;
