#region License Information (GPL v3)

/*
    XerahS - The Avalonia UI implementation of ShareX
    Copyright (c) 2007-2026 ShareX Team

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

    Optionally you can also view the license at <http://www.gnu.org/licenses/>.
*/

#endregion License Information (GPL v3)

using System.Text;
using XerahS.Common;

namespace XerahS.Indexer
{
    public class IndexerMarkdown : Indexer
    {
        private readonly StringBuilder _content = new();

        public IndexerMarkdown(IndexerSettings indexerSettings) : base(indexerSettings)
        {
        }

        public override string Index(string folderPath)
        {
            FolderInfo folderInfo = GetFolderInfo(folderPath);
            folderInfo.Update();

            _content.Clear();
            _content.Append("# Directory Index: ");
            _content.AppendLine(EscapeMarkdown(folderInfo.FolderName));
            _content.AppendLine();

            IndexFolder(folderInfo);

            if (settings.AddFooter)
            {
                _content.AppendLine();
                _content.AppendLine("---");
                _content.AppendLine();
                _content.AppendLine($"Generated by {AppResources.AppName} Directory Indexer on {DateTime.UtcNow:yyyy-MM-dd 'at' HH:mm:ss 'UTC'}. Latest version can be downloaded from: {Links.XerahSWebsite}");
            }

            return _content.ToString().TrimEnd();
        }

        protected override void IndexFolder(FolderInfo dir, int level = 0)
        {
            if (level > 0)
            {
                AppendFolderRow(dir, level);
            }

            foreach (FolderInfo folder in dir.Folders)
            {
                IndexFolder(folder, level + 1);
            }

            foreach (FileInfo file in dir.Files)
            {
                AppendFileRow(file, level + 1);
            }
        }

        private void AppendFolderRow(FolderInfo folder, int level)
        {
            _content.Append(GetIndent(level - 1));
            _content.Append("- **");
            _content.Append(EscapeMarkdown(folder.FolderName));
            _content.Append("/**");

            if (settings.ShowSizeInfo && folder.Size > 0)
            {
                _content.Append(" (");
                _content.Append(folder.Size.ToSizeString(settings.BinaryUnits));
                _content.Append(')');
            }

            _content.AppendLine();
        }

        private void AppendFileRow(FileInfo file, int level)
        {
            _content.Append(GetIndent(level - 1));
            _content.Append("- ");
            _content.Append(EscapeMarkdown(file.Name));

            if (settings.ShowSizeInfo)
            {
                _content.Append(" (");
                _content.Append(file.Length.ToSizeString(settings.BinaryUnits));
                _content.Append(')');
            }

            _content.AppendLine();
        }

        private static string GetIndent(int level)
        {
            return new string(' ', Math.Max(0, level) * 2);
        }

        private static string EscapeMarkdown(string value)
        {
            StringBuilder escaped = new(value.Length);

            foreach (char c in value)
            {
                if (c is '\\' or '`' or '*' or '_' or '{' or '}' or '[' or ']' or '<' or '>' or '(' or ')' or '#' or '+' or '-' or '.' or '!' or '|')
                {
                    escaped.Append('\\');
                }

                escaped.Append(c);
            }

            return escaped.ToString();
        }
    }
}
