/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=infrastructure/cloudflare/scheduler/wrangler.jsonc --include-runtime=false infrastructure/cloudflare/scheduler/worker-configuration.d.ts` (hash: f0d2e7002ce3098e07f34a1f7a96ee5c)
interface __BaseEnv_Env {
  APP_ORIGIN?: "https://staging.xerahs.com" | "https://xerahs.com";
  CRON_SECRET?: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
  }
  interface StagingEnv {
    APP_ORIGIN: "https://staging.xerahs.com";
    CRON_SECRET: string;
  }
  interface ProductionEnv {
    APP_ORIGIN: "https://xerahs.com";
    CRON_SECRET: string;
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "APP_ORIGIN" | "CRON_SECRET">
  > {}
}
